/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MintRequest {
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export interface NFT {
  'tokenId' : TokenId,
  'owner' : Principal,
  'metadata' : NFTMetadata,
  'mintedAt' : bigint,
}
export interface NFTCollection {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface NFTItem {
  'id' : string,
  'title' : string,
  'tokenId' : [] | [bigint],
  'imageData' : ExternalBlob,
  'collectionId' : string,
  'owner' : [] | [Principal],
  'minted' : boolean,
  'description' : string,
  'mintedAt' : [] | [bigint],
  'price' : bigint,
}
export interface NFTMetadata {
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export type TokenId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCollection' : ActorMethod<[string, string, string], undefined>,
  'addNFT' : ActorMethod<
    [string, string, string, string, ExternalBlob, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countMyNFTs' : ActorMethod<[], bigint>,
  'deleteCollection' : ActorMethod<[string], undefined>,
  'deleteNFT' : ActorMethod<[string], undefined>,
  'getAllCollections' : ActorMethod<[], Array<NFTCollection>>,
  'getAllNFTs' : ActorMethod<[], Array<NFTItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIssuedNFT' : ActorMethod<[TokenId], [] | [NFT]>,
  'getNFT' : ActorMethod<[string], [] | [NFTItem]>,
  'getNFTsByCollection' : ActorMethod<[string], Array<NFTItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllNFTs' : ActorMethod<[], Array<NFT>>,
  'listMyNFTs' : ActorMethod<[], Array<NFT>>,
  'listNFTsByPrincipal' : ActorMethod<[Principal], Array<NFT>>,
  'mintNFT' : ActorMethod<[MintRequest], TokenId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCollection' : ActorMethod<[string, string, string], undefined>,
  'updateNFT' : ActorMethod<
    [string, string, string, string, ExternalBlob, bigint],
    undefined
  >,
  'uploadImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];