/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NFTCollection = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const NFTItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'tokenId' : IDL.Opt(IDL.Nat),
  'imageData' : ExternalBlob,
  'collectionId' : IDL.Text,
  'owner' : IDL.Opt(IDL.Principal),
  'minted' : IDL.Bool,
  'description' : IDL.Text,
  'mintedAt' : IDL.Opt(IDL.Int),
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TokenId = IDL.Nat;
export const NFTMetadata = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const NFT = IDL.Record({
  'tokenId' : TokenId,
  'owner' : IDL.Principal,
  'metadata' : NFTMetadata,
  'mintedAt' : IDL.Int,
});
export const MintRequest = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCollection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addNFT' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'countMyNFTs' : IDL.Func([], [IDL.Nat], ['query']),
  'deleteCollection' : IDL.Func([IDL.Text], [], []),
  'deleteNFT' : IDL.Func([IDL.Text], [], []),
  'getAllCollections' : IDL.Func([], [IDL.Vec(NFTCollection)], ['query']),
  'getAllNFTs' : IDL.Func([], [IDL.Vec(NFTItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIssuedNFT' : IDL.Func([TokenId], [IDL.Opt(NFT)], ['query']),
  'getNFT' : IDL.Func([IDL.Text], [IDL.Opt(NFTItem)], ['query']),
  'getNFTsByCollection' : IDL.Func([IDL.Text], [IDL.Vec(NFTItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllNFTs' : IDL.Func([], [IDL.Vec(NFT)], ['query']),
  'listMyNFTs' : IDL.Func([], [IDL.Vec(NFT)], ['query']),
  'listNFTsByPrincipal' : IDL.Func([IDL.Principal], [IDL.Vec(NFT)], ['query']),
  'mintNFT' : IDL.Func([MintRequest], [TokenId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCollection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateNFT' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
      [],
      [],
    ),
  'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NFTCollection = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const NFTItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'tokenId' : IDL.Opt(IDL.Nat),
    'imageData' : ExternalBlob,
    'collectionId' : IDL.Text,
    'owner' : IDL.Opt(IDL.Principal),
    'minted' : IDL.Bool,
    'description' : IDL.Text,
    'mintedAt' : IDL.Opt(IDL.Int),
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TokenId = IDL.Nat;
  const NFTMetadata = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const NFT = IDL.Record({
    'tokenId' : TokenId,
    'owner' : IDL.Principal,
    'metadata' : NFTMetadata,
    'mintedAt' : IDL.Int,
  });
  const MintRequest = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCollection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addNFT' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'countMyNFTs' : IDL.Func([], [IDL.Nat], ['query']),
    'deleteCollection' : IDL.Func([IDL.Text], [], []),
    'deleteNFT' : IDL.Func([IDL.Text], [], []),
    'getAllCollections' : IDL.Func([], [IDL.Vec(NFTCollection)], ['query']),
    'getAllNFTs' : IDL.Func([], [IDL.Vec(NFTItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIssuedNFT' : IDL.Func([TokenId], [IDL.Opt(NFT)], ['query']),
    'getNFT' : IDL.Func([IDL.Text], [IDL.Opt(NFTItem)], ['query']),
    'getNFTsByCollection' : IDL.Func([IDL.Text], [IDL.Vec(NFTItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllNFTs' : IDL.Func([], [IDL.Vec(NFT)], ['query']),
    'listMyNFTs' : IDL.Func([], [IDL.Vec(NFT)], ['query']),
    'listNFTsByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(NFT)],
        ['query'],
      ),
    'mintNFT' : IDL.Func([MintRequest], [TokenId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCollection' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateNFT' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Nat],
        [],
        [],
      ),
    'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };